apiVersion: v2
name: idrm
description: IDRM AI Template Helm Chart
type: application
version: 0.1.0
appVersion: "1.0.0"

keywords:
  - go-zero
  - microservices
  - api
  - rpc
  - job
  - consumer

maintainers:
  - name: IDRM Team
    email: team@example.com
