apiVersion: v1
kind: Secret
metadata:
  name: {{ include "idrm.fullname" . }}-secret
  labels:
    {{- include "idrm.labels" . | nindent 4 }}
type: Opaque
data:
  mysql-password: {{ .Values.secrets.mysql.password | b64enc | quote }}
